services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: db
    depends_on:
      db:
        condition: service_healthy
    # run migrations then start server
    command: >
      sh -c "wait-for-it -s -t 30 db:5432 -- \
        alembic upgrade head && \
        python seed_admin.py && \
        uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app

volumes:
  pgdata_test:
