version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: asikh-oms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always
    networks:
      - asikh-network

networks:
  asikh-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
