name: Deploy Backend to Heroku Test

on:
  push:
    branches:
      - develop  # Trigger deployment on push to develop branch
    paths:
      - 'backend/**'  # Only trigger when changes are made to backend files

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: asikh_oms
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.6'  # Match the version in runtime.txt

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Test stage removed

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Create Heroku app if it doesn't exist
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          # Check if app exists, create if it doesn't
          if ! heroku apps:info asikh-oms-test &> /dev/null; then
            echo "Creating Heroku app: asikh-oms-test"
            heroku create asikh-oms-test
            heroku addons:create heroku-postgresql:hobby-dev --app asikh-oms-test
          else
            echo "Heroku app asikh-oms-test already exists"
          fi

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "asikh-oms-test"  # Your Heroku app name
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend"  # Specify the directory containing your backend code
          force: true  # Force push to override any conflicts
          
      - name: Run database migrations
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku run "cd /app && alembic upgrade head" --app asikh-oms-test
